# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7iFh_SSsFgWQzjD8_gPxbp-wHaIOm2D
"""

"""
=============================================================
AI-Powered Business Intelligence: Buyer Propensity Model
Main Implementation Script
Student: ARJUN | Enrollment: O24MCA110870
=============================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report, roc_curve
)
import warnings
warnings.filterwarnings('ignore')

# ===== STEP 1: DATA INGESTION =====
print("=" * 60)
print("STEP 1: LOADING DATASETS")
print("=" * 60)

# Load training dataset (labeled data)
df_sales = pd.read_csv('SalesTraining.csv')

# Load prospect dataset (unlabeled data to be scored)
df_prospects = pd.read_csv('ProspectiveBuyer.csv')

print(f"Sales Training dataset shape: {df_sales.shape}")
print(f"Columns: {list(df_sales.columns)}")
print(f"\nBuyer distribution:")
print(df_sales['Buyer'].value_counts())
print(f"Buyer rate: {df_sales['Buyer'].mean():.2%}")

print(f"\nProspective Buyer dataset shape: {df_prospects.shape}")
print(f"Columns: {list(df_prospects.columns)}")

"""
Expected Output:
Sales Training dataset shape: (7819, 13)
Columns: ['Age', 'MaritalStatus', 'Gender', 'YearlyIncome',
          'TotalChildren', 'NumberChildrenAtHome', 'Education',
          'Occupation', 'HouseOwnerFlag', 'NumberCarsOwned',
          'StateProvinceCode', 'PostalCode', 'Buyer']

Buyer distribution:
Buyer
0    4250
1    3569
Name: count, dtype: int64
Buyer rate: 45.65%

Prospective Buyer dataset shape: (2059, 17)
"""

# ===== STEP 2: DATA CLEANING =====
print("\n" + "=" * 60)
print("STEP 2: DATA CLEANING & PREPROCESSING")
print("=" * 60)

# Check for missing values
print("Missing values - Sales Training:")
print(df_sales.isnull().sum())
# Result: All 0 - dataset is complete

print("\nMissing values - Prospective Buyers:")
print(df_prospects.isnull().sum())
# Result: All 0 - dataset is complete

# ===== FIX TRUNCATED EDUCATION VALUES =====
# ProspectiveBuyer.csv has truncated Education values
# e.g., "Partial Hi" should be "Partial High School"
print("\nProspect Education values (before fix):")
print(df_prospects['Education'].unique())

education_mapping = {
    'Partial Hi': 'Partial High School',
    'Partial High School': 'Partial High School',
    'High Schoo': 'High School',
    'High School': 'High School',
    'Graduate D': 'Graduate Degree',
    'Graduate Degree': 'Graduate Degree',
    'Partial Co': 'Partial College',
    'Partial College': 'Partial College',
    'Bachelors': 'Bachelors'
}

df_prospects['Education'] = df_prospects['Education'].apply(
    lambda x: education_mapping.get(x, x)
)

print("\nProspect Education values (after fix):")
print(df_prospects['Education'].unique())

# Verify that Education values now match between datasets
sales_edu = set(df_sales['Education'].unique())
prospect_edu = set(df_prospects['Education'].unique())
print(f"\nEducation values match: {sales_edu == prospect_edu}")
print(f"Sales Education: {sorted(sales_edu)}")
print(f"Prospect Education: {sorted(prospect_edu)}")

# ===== DEFINE COMMON FEATURES =====
common_features = [
    'Age', 'MaritalStatus', 'Gender', 'YearlyIncome',
    'TotalChildren', 'NumberChildrenAtHome', 'Education',
    'Occupation', 'HouseOwnerFlag', 'NumberCarsOwned',
    'StateProvinceCode', 'PostalCode'
]

# Extract feature matrices
X_train_raw = df_sales[common_features].copy()
y_all = df_sales['Buyer'].copy()
X_prospect_raw = df_prospects[common_features].copy()

print(f"\nTraining features shape: {X_train_raw.shape}")
print(f"Target variable shape: {y_all.shape}")
print(f"Prospect features shape: {X_prospect_raw.shape}")

# ===== STEP 3: FEATURE ENGINEERING =====
print("\n" + "=" * 60)
print("STEP 3: FEATURE ENGINEERING & ENCODING")
print("=" * 60)

# ===== BINARY ENCODING =====
# MaritalStatus: M=1 (Married), S=0 (Single)
# Gender: M=1 (Male), F=0 (Female)
binary_mappings = {
    'MaritalStatus': {'M': 1, 'S': 0},
    'Gender': {'M': 1, 'F': 0}
}

for col, mapping in binary_mappings.items():
    X_train_raw[col] = X_train_raw[col].map(mapping)
    X_prospect_raw[col] = X_prospect_raw[col].map(mapping)

print("Binary encoding applied: MaritalStatus, Gender")

# ===== ONE-HOT ENCODING =====
# Must encode BOTH datasets together to ensure identical feature columns
# This prevents feature mismatch between training and scoring

multi_cat_cols = ['Education', 'Occupation', 'StateProvinceCode', 'PostalCode']

# Add source labels before combining
X_train_raw['_source'] = 'train'
X_prospect_raw['_source'] = 'prospect'

# Combine datasets for consistent encoding
combined = pd.concat([X_train_raw, X_prospect_raw], axis=0, ignore_index=True)

# Apply one-hot encoding
combined_encoded = pd.get_dummies(
    combined,
    columns=multi_cat_cols,
    drop_first=True
)

# Split back into training and prospect datasets
X_all_encoded = combined_encoded[combined_encoded['_source'] == 'train'].drop(
    columns=['_source']
).reset_index(drop=True)

X_prospects_encoded = combined_encoded[combined_encoded['_source'] == 'prospect'].drop(
    columns=['_source']
).reset_index(drop=True)

print(f"After encoding - Training features: {X_all_encoded.shape}")
print(f"After encoding - Prospect features: {X_prospects_encoded.shape}")
print(f"Feature columns (first 10): {list(X_all_encoded.columns[:10])}")

# ===== TRAIN-TEST SPLIT =====
X_train, X_test, y_train, y_test = train_test_split(
    X_all_encoded, y_all,
    test_size=0.2,
    random_state=42,
    stratify=y_all  # Preserve class balance in both splits
)

print(f"\nTrain set: {X_train.shape[0]} records")
print(f"Test set: {X_test.shape[0]} records")
print(f"Train Buyer rate: {y_train.mean():.2%}")
print(f"Test Buyer rate: {y_test.mean():.2%}")

# ===== STEP 4: EXPLORATORY DATA ANALYSIS =====
print("\n" + "=" * 60)
print("STEP 4: EXPLORATORY DATA ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle('Exploratory Data Analysis: Customer Purchase Behavior',
             fontsize=16, fontweight='bold')

# 1. Buyer Distribution
buyer_counts = df_sales['Buyer'].value_counts()
axes[0,0].bar(['Non-Buyer (0)', 'Buyer (1)'],
               buyer_counts.values,
               color=['#e74c3c', '#2ecc71'],
               edgecolor='black', linewidth=0.5)
axes[0,0].set_title('Buyer Distribution', fontweight='bold')
axes[0,0].set_ylabel('Count')
for i, v in enumerate(buyer_counts.values):
    axes[0,0].text(i, v + 30, f'{v:,}\n({v/len(df_sales)*100:.1f}%)',
                    ha='center', fontweight='bold')

# 2. Age Distribution by Buyer Status
buyers_age = df_sales[df_sales['Buyer'] == 1]['Age']
non_buyers_age = df_sales[df_sales['Buyer'] == 0]['Age']
axes[0,1].hist(non_buyers_age, alpha=0.6, bins=20,
               color='#e74c3c', label='Non-Buyer', edgecolor='black')
axes[0,1].hist(buyers_age, alpha=0.6, bins=20,
               color='#2ecc71', label='Buyer', edgecolor='black')
axes[0,1].set_title('Age Distribution by Buyer Status', fontweight='bold')
axes[0,1].set_xlabel('Age')
axes[0,1].set_ylabel('Count')
axes[0,1].legend()

# 3. Income Distribution by Buyer Status
buyers_income = df_sales[df_sales['Buyer'] == 1]['YearlyIncome']
non_buyers_income = df_sales[df_sales['Buyer'] == 0]['YearlyIncome']
axes[0,2].hist(non_buyers_income/1000, alpha=0.6, bins=20,
               color='#e74c3c', label='Non-Buyer', edgecolor='black')
axes[0,2].hist(buyers_income/1000, alpha=0.6, bins=20,
               color='#2ecc71', label='Buyer', edgecolor='black')
axes[0,2].set_title('Income Distribution by Buyer Status', fontweight='bold')
axes[0,2].set_xlabel('Yearly Income ($K)')
axes[0,2].set_ylabel('Count')
axes[0,2].legend()

# 4. Education vs Buyer Rate
edu_buyer_rate = df_sales.groupby('Education')['Buyer'].mean().sort_values(ascending=True)
colors_edu = ['#2ecc71' if x >= 0.5 else '#e74c3c' for x in edu_buyer_rate.values]
axes[1,0].barh(edu_buyer_rate.index, edu_buyer_rate.values * 100,
                color=colors_edu, edgecolor='black')
axes[1,0].set_title('Buyer Rate by Education Level', fontweight='bold')
axes[1,0].set_xlabel('Buyer Rate (%)')
axes[1,0].axvline(x=45.65, color='navy', linestyle='--', label='Overall Rate')
axes[1,0].legend()

# 5. Occupation vs Buyer Rate
occ_buyer_rate = df_sales.groupby('Occupation')['Buyer'].mean().sort_values(ascending=True)
colors_occ = ['#2ecc71' if x >= 0.5 else '#e74c3c' for x in occ_buyer_rate.values]
axes[1,1].barh(occ_buyer_rate.index, occ_buyer_rate.values * 100,
                color=colors_occ, edgecolor='black')
axes[1,1].set_title('Buyer Rate by Occupation', fontweight='bold')
axes[1,1].set_xlabel('Buyer Rate (%)')
axes[1,1].axvline(x=45.65, color='navy', linestyle='--', label='Overall Rate')
axes[1,1].legend()

# 6. Cars Owned vs Buyer Rate
cars_buyer_rate = df_sales.groupby('NumberCarsOwned')['Buyer'].mean()
axes[1,2].bar(cars_buyer_rate.index, cars_buyer_rate.values * 100,
               color='#3498db', edgecolor='black')
axes[1,2].set_title('Buyer Rate by Number of Cars Owned', fontweight='bold')
axes[1,2].set_xlabel('Number of Cars Owned')
axes[1,2].set_ylabel('Buyer Rate (%)')
axes[1,2].axhline(y=45.65, color='red', linestyle='--', label='Overall Rate')
axes[1,2].legend()

plt.tight_layout()
plt.savefig('eda_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("EDA plots saved: eda_analysis.png")

# ===== STEP 5: MODEL TRAINING & EVALUATION =====
print("\n" + "=" * 60)
print("STEP 5: MODEL TRAINING AND EVALUATION")
print("=" * 60)

# ===== MODEL 1: LOGISTIC REGRESSION =====
print("\n--- Training Logistic Regression ---")
lr_model = LogisticRegression(max_iter=1000, random_state=42, C=1.0)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_prob = lr_model.predict_proba(X_test)[:, 1]

lr_results = {
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_score(y_test, lr_pred),
    'Precision': precision_score(y_test, lr_pred),
    'Recall': recall_score(y_test, lr_pred),
    'F1_Score': f1_score(y_test, lr_pred),
    'AUC_ROC': roc_auc_score(y_test, lr_prob)
}
print(f"Logistic Regression Results:")
print(classification_report(y_test, lr_pred,
      target_names=['Non-Buyer', 'Buyer']))

# ===== MODEL 2: RANDOM FOREST CLASSIFIER =====
print("\n--- Training Random Forest Classifier ---")
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_prob = rf_model.predict_proba(X_test)[:, 1]

rf_results = {
    'Model': 'Random Forest',
    'Accuracy': accuracy_score(y_test, rf_pred),
    'Precision': precision_score(y_test, rf_pred),
    'Recall': recall_score(y_test, rf_pred),
    'F1_Score': f1_score(y_test, rf_pred),
    'AUC_ROC': roc_auc_score(y_test, rf_prob)
}
print(f"Random Forest Results:")
print(classification_report(y_test, rf_pred,
      target_names=['Non-Buyer', 'Buyer']))

# ===== MODEL 3: DECISION TREE CLASSIFIER =====
print("\n--- Training Decision Tree Classifier ---")
dt_model = DecisionTreeClassifier(
    max_depth=8,
    min_samples_split=10,
    random_state=42
)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_prob = dt_model.predict_proba(X_test)[:, 1]

dt_results = {
    'Model': 'Decision Tree',
    'Accuracy': accuracy_score(y_test, dt_pred),
    'Precision': precision_score(y_test, dt_pred),
    'Recall': recall_score(y_test, dt_pred),
    'F1_Score': f1_score(y_test, dt_pred),
    'AUC_ROC': roc_auc_score(y_test, dt_prob)
}
print(f"Decision Tree Results:")
print(classification_report(y_test, dt_pred,
      target_names=['Non-Buyer', 'Buyer']))

# ===== MODEL COMPARISON =====
comparison_df = pd.DataFrame([lr_results, rf_results, dt_results])
print("\n" + "=" * 70)
print("MODEL COMPARISON SUMMARY")
print("=" * 70)
print(comparison_df.to_string(index=False, float_format='%.4f'))

# Select best model based on AUC-ROC
best_idx = comparison_df['AUC_ROC'].idxmax()
best_model_name = comparison_df.loc[best_idx, 'Model']
print(f"\n✅ Best Model: {best_model_name}")
print(f"   AUC-ROC: {comparison_df.loc[best_idx, 'AUC_ROC']:.4f}")
print(f"   Accuracy: {comparison_df.loc[best_idx, 'Accuracy']:.4f}")

# Save model comparison
comparison_df.to_csv('model_comparison.csv', index=False)
print("\nModel comparison saved: model_comparison.csv")

# ===== STEP 6: VISUALIZATION =====
print("\n" + "=" * 60)
print("STEP 6: GENERATING EVALUATION VISUALIZATIONS")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Model Evaluation: Confusion Matrices',
             fontsize=14, fontweight='bold')

models_data = [
    ('Logistic Regression', lr_pred, '#3498db'),
    ('Random Forest', rf_pred, '#2ecc71'),
    ('Decision Tree', dt_pred, '#e74c3c')
]

for idx, (name, pred, color) in enumerate(models_data):
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                ax=axes[idx],
                xticklabels=['Non-Buyer', 'Buyer'],
                yticklabels=['Non-Buyer', 'Buyer'])
    axes[idx].set_title(f'{name}', fontweight='bold')
    axes[idx].set_ylabel('Actual')
    axes[idx].set_xlabel('Predicted')

plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=150, bbox_inches='tight')
plt.show()

# ROC Curves
fig, ax = plt.subplots(figsize=(8, 6))
models_roc = [
    ('Logistic Regression', lr_prob, '#3498db'),
    ('Random Forest', rf_prob, '#2ecc71'),
    ('Decision Tree', dt_prob, '#e74c3c')
]

for name, prob, color in models_roc:
    fpr, tpr, _ = roc_curve(y_test, prob)
    auc = roc_auc_score(y_test, prob)
    ax.plot(fpr, tpr, color=color, linewidth=2,
            label=f'{name} (AUC = {auc:.3f})')

ax.plot([0, 1], [0, 1], 'k--', linewidth=1, label='Random Classifier')
ax.set_xlabel('False Positive Rate', fontsize=12)
ax.set_ylabel('True Positive Rate', fontsize=12)
ax.set_title('ROC Curves — Model Comparison', fontsize=14, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('roc_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print("Visualizations saved: confusion_matrices.png, roc_curves.png")

# ===== STEP 7: FEATURE IMPORTANCE =====
print("\n" + "=" * 60)
print("STEP 7: FEATURE IMPORTANCE ANALYSIS")
print("=" * 60)

# Extract feature importances from Random Forest
feature_names = X_all_encoded.columns.tolist()
importances = rf_model.feature_importances_

feature_imp_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False).reset_index(drop=True)

feature_imp_df['Rank'] = range(1, len(feature_imp_df) + 1)

# Display top 15 features
print("\nTop 15 Most Important Features:")
print(feature_imp_df.head(15).to_string(index=False))

# Plot top 15 features
top_features = feature_imp_df.head(15)
plt.figure(figsize=(10, 8))
colors = ['#2ecc71' if i < 5 else '#3498db' if i < 10 else '#e74c3c'
          for i in range(len(top_features))]
plt.barh(range(len(top_features)),
         top_features['Importance'].values,
         color=colors,
         edgecolor='black', linewidth=0.5)
plt.yticks(range(len(top_features)),
           top_features['Feature'].values, fontsize=10)
plt.xlabel('Feature Importance Score', fontsize=12)
plt.title('Top 15 Features Predicting Buyer Propensity\n(Random Forest)',
          fontsize=13, fontweight='bold')
plt.gca().invert_yaxis()

# Add value labels
for i, v in enumerate(top_features['Importance'].values):
    plt.text(v + 0.001, i, f'{v:.4f}', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

# Save feature importance
feature_imp_df.to_csv('feature_importance.csv', index=False)
print("Feature importance saved: feature_importance.csv")

# ===== STEP 8: PROSPECT SCORING =====
print("\n" + "=" * 60)
print("STEP 8: SCORING PROSPECTIVE BUYERS")
print("=" * 60)

# Apply the best model (Random Forest) to all 2,059 prospects
prospect_probabilities = rf_model.predict_proba(X_prospects_encoded)[:, 1]
prospect_predictions = rf_model.predict(X_prospects_encoded)

# Assign priority tiers based on probability thresholds
def assign_priority_tier(prob):
    if prob >= 0.70:
        return 'High'
    elif prob >= 0.40:
        return 'Medium'
    else:
        return 'Low'

priority_tiers = [assign_priority_tier(p) for p in prospect_probabilities]

# Create scored prospects output
scored_prospects = df_prospects[['ProspectiveBuyerKey', 'ProspectAlternateKey',
                                  'FirstName', 'LastName', 'Age', 'Gender',
                                  'MaritalStatus', 'YearlyIncome', 'Education',
                                  'Occupation', 'HouseOwnerFlag',
                                  'NumberCarsOwned', 'City',
                                  'StateProvinceCode', 'PostalCode']].copy()

scored_prospects['BuyProbability'] = prospect_probabilities.round(4)
scored_prospects['PredictedBuyer'] = prospect_predictions
scored_prospects['PriorityTier'] = priority_tiers
scored_prospects['ProbabilityPct'] = (prospect_probabilities * 100).round(1)

# Sort by probability (highest first for sales prioritization)
scored_prospects = scored_prospects.sort_values(
    'BuyProbability', ascending=False
).reset_index(drop=True)

# Summary statistics
print(f"\nScoring Complete!")
print(f"Total Prospects Scored: {len(scored_prospects):,}")
print(f"\nPriority Tier Distribution:")
tier_counts = scored_prospects['PriorityTier'].value_counts()
for tier in ['High', 'Medium', 'Low']:
    count = tier_counts.get(tier, 0)
    pct = count / len(scored_prospects) * 100
    print(f"  {tier}: {count:,} ({pct:.1f}%)")

print(f"\nProbability Statistics:")
print(f"  Mean: {prospect_probabilities.mean():.4f} ({prospect_probabilities.mean()*100:.1f}%)")
print(f"  Median: {np.median(prospect_probabilities):.4f}")
print(f"  Min: {prospect_probabilities.min():.4f}")
print(f"  Max: {prospect_probabilities.max():.4f}")

print(f"\nTop 10 Highest-Priority Prospects:")
print(scored_prospects[['FirstName', 'LastName', 'Age', 'Occupation',
                          'YearlyIncome', 'BuyProbability',
                          'PriorityTier']].head(10).to_string(index=False))

# Save scored prospects
scored_prospects.to_csv('scored_prospects.csv', index=False)
print(f"\nScored prospects saved: scored_prospects.csv")

# ===== POWER BI PYTHON VISUAL: PROBABILITY DISTRIBUTION =====
# This script runs INSIDE Power BI as a Python Visual
# 'dataset' is the DataFrame automatically passed by Power BI

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# 'dataset' contains: BuyProbability, PriorityTier
# (fields dragged into the Python visual in Power BI)

fig, ax = plt.subplots(figsize=(8, 5))

# Color code by priority tier
high = scored_prospects[scored_prospects['PriorityTier'] == 'High']['BuyProbability']
medium = scored_prospects[scored_prospects['PriorityTier'] == 'Medium']['BuyProbability']
low = scored_prospects[scored_prospects['PriorityTier'] == 'Low']['BuyProbability']

ax.hist(low, bins=20, alpha=0.7, color='#e74c3c',
        label=f'Low ({len(low)})', edgecolor='white')
ax.hist(medium, bins=20, alpha=0.7, color='#f39c12',
        label=f'Medium ({len(medium)})', edgecolor='white')
ax.hist(high, bins=20, alpha=0.7, color='#2ecc71',
        label=f'High ({len(high)})', edgecolor='white')

ax.axvline(x=0.40, color='orange', linestyle='--',
           linewidth=1.5, label='Low/Medium Threshold (0.40)')
ax.axvline(x=0.70, color='green', linestyle='--',
           linewidth=1.5, label='Medium/High Threshold (0.70)')

ax.set_xlabel('Purchase Probability Score', fontsize=11)
ax.set_ylabel('Number of Prospects', fontsize=11)
ax.set_title('Prospect Purchase Probability Distribution\nby Priority Tier',
             fontsize=12, fontweight='bold')
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

